### ISSUE TITLE
I want to be able to use virtual memory in 4KiB granule

### ISSUE THREAD

**Issue by matix522** [matix522/uranos#8]

**Comment by piaskowyk** [comment]
I have the same problem. Could you fix it soon?

**Comment by matix522** [comment]
yes

**Comment by Yacubane** [comment]
This issue is here for 3 months, could we get approximate date, when will it be fixed?

**Comment by piaskowyk** [comment]
Ar u still alive?

**Comment by pk1890** [comment]
Please, be patient. @matix522 is working day and night for 3 months now. It will be done as soon as he implements it

**Comment by Marwin34** [comment]
Why is this issue still open? I thought you have enough time to resolve it.

**Comment by piaskowyk** [comment]
I haven't seen any tests. Will you plan to improve text coverage? I think that is really important.

**Comment by Yacubane** [comment]
> I haven't seen any tests. Will you plan to improve text coverage? I think that is really important.

I also find lack of text coverage really sad. Do you have guys any document about "selected aspects of realization", just checking your code and this document would be really interesting to read, you should do it! 👌🧔🏾👍🥃

**Comment by piaskowyk** [comment]
@pk1890 Could I use virtual memory in 5KiB granul? It is discrimination odd numbers. 🤨

**Comment by Yacubane** [comment]
> @pk1890 Could I use virtual memory in 5KiB granul? It is discrimination odd numbers. 🤨

Not only odd numbers but even also, because they use only one even number... **_FOUR NUMBER SUPERMACY_**
Please give possibility to make granule of **ANY** number. Not only integer but **real** also. Every number deserves to be size of granule!

**Comment by piaskowyk** [comment]
Freedom for granulated size!

**Comment by piaskowyk** [comment]
Freedom for size of granule!

**Comment by matix522** [comment]
I'm giving up

**Comment by piaskowyk** [comment]
@matix522 Remeber about this: https://bit.ly/2UjaZr6
